import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Button } from '@/components/ui/button'
import Hearts from '@/components/Icons/Hearts'
import AlbumsIcon from '@/components/Icons/Albums'
import GallaryIcon from '@/components/Icons/Gallary'
import Link from 'next/link'
import cloudinary from "cloudinary"
import { Folder } from './albums/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function Sidemenu(){

  const {folders} = (await cloudinary.v2.api.root_folders()) as {
    folders: Folder[];
  };

  return(

<div className="pb-12 w-1/5">
      <div className="space-y-4 py-4">
        <div className="px-3 py-2">
          <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
            Manage
          </h2>
          <div className="space-y-1">
            <Button
            asChild 
            variant="secondary" 
            className="w-full justify-start flex gap-4">
            <Link href="/gallary">
           <GallaryIcon/>
              Gallary
              </Link>
            </Button>
            <Button asChild variant="ghost" className="w-full justify-start flex gap-4">
              <Link href={"/albums"}>
              <AlbumsIcon/>
              Albums
              </Link>
            </Button>
            {folders.map(folder =>
               <Button variant="ghost " className="ml-8 pl-4 w-full justify-start flex gap-4" 
               asChild key={folder.name}>
              <Link href={`/albums/${folder.path}`}>
           {folder.name}
           Favorites
           </Link>
            </Button>)}
            <Button asChild variant="ghost" 
            className="w-full justify-start flex gap-4">
          <Link href="/favorite">
           <Hearts/>
           Favorites
           </Link>
            </Button>
          </div>
        </div>
</div>
    </div>
  
  )

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
      
        <div className="border-b ">
          <div className="container mx-auto flex h-16 items-center px-4">
           Photos App
            <div className="ml-auto flex items-center space-x-4">
            <Avatar>
      <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
      <AvatarFallback>CN</AvatarFallback>
    </Avatar>
            </div>
          </div>
        </div>
        <div className="flex">
        <Sidemenu/>
        <div className="w-full px-4 pt-8" >{children}</div>
        </div>
        </body>
    </html>
  )
}
